### PR TITLE
Enable HTTP/2 for all sites where we have HTTPS

### LINKED ISSUE #10: HTTP/2 support
I think that we should enable HTTP/2 support for both codingteam.org.ru and loglist.net sites.

### PR DESCRIPTION
**Pull request by Minoru**
Fixes #10.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
Honestly I'm not sure if we have nginx that supports HTTP/2. Need to check.

**Comment by Minoru** [comment]
I checked; we do.

**Comment by Minoru** [comment]
To be specific: HTTP/2 is supported [since 1.9.5](https://www.nginx.com/blog/nginx-1-9-5/), and we have 1.10.0:

```console
$ curl --verbose https://www.loglist.net
[…]
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.10.0 (Ubuntu)
[…]
```

**Comment by ForNeVeR** [comment]
Thanks a lot, it works!

**Pull request merged**
