### PR TITLE
License: initialize as MIT

### PR DESCRIPTION
**Pull request by ForNeVeR**
Suddenly I've found that we have no license in this project. Hereby I propose to use MIT license, because we're mainly publishing infrastructural code here.

### CODE REVIEW

**Comment by rexim** [comment]
We also have this [masterpiece](https://github.com/codingteam/devops/blob/ff005ab3ee2fd6555acb3960ba76356fb13fe31d/docs/devops.png)

What license should it be distributed under?

**Comment by ForNeVeR** [comment]
This is "the associated documentation file" as stated by the license.

That said, the original image was taken from Wikipedia, so I'd like to redraw that. Lemme do it!

**Comment by ForNeVeR** [comment]
Done; please check again.

**Comment by ForNeVeR** [comment]
Thanks!

**Pull request merged**
